let token,poller,centralKey='';
const $=x=>document.querySelector(x);
const api=async(p,o={})=>{const r=await fetch(p,{...o,headers:{'Content-Type':'application/json',Authorization:'Bearer '+token,...(centralKey?{'X-Central-Access':centralKey}:{})}});const d=await r.json();if(!r.ok)throw Error(d.error||'Erreur de connexion');return d};
const dt=x=>x?new Date(x).toLocaleString('fr-FR',{dateStyle:'medium',timeStyle:'short'}):'—';
const esc=x=>String(x||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const workTime=m=>`${Math.floor(m/60)} h ${m%60} min`;
function showTab(n){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===n));document.querySelectorAll('.tab-panel').forEach(p=>p.hidden=p.dataset.panel!==n);if(n==='central'&&centralKey)loadCentral()}
function requestButtons(x){if(x.status==='request_received')return ` <button data-id="${x.id}" data-paid>Wave reçu</button> <button class="secondary" data-id="${x.id}" data-decision="rejected">Refuser</button>`;if(x.status==='payment_confirmed')return ` <button data-id="${x.id}" data-decision="approved">Valider</button> <button class="secondary" data-id="${x.id}" data-decision="rejected">Refuser</button>`;return ''}
function claimButtons(x){return `<select data-claim-status="${x.id}"><option value="open" ${x.status==='open'?'selected':''}>Nouvelle</option><option value="in_review" ${x.status==='in_review'?'selected':''}>En cours</option><option value="resolved" ${x.status==='resolved'?'selected':''}>Résolue</option><option value="closed" ${x.status==='closed'?'selected':''}>Clôturée</option></select><input data-claim-note="${x.id}" placeholder="Réponse au client"><button data-claim-save="${x.id}">Mettre à jour</button>`}
async function load(){try{const d=await api('/api/admin/overview');$('#gate').hidden=true;$('#panel').hidden=false;$('#adminlogout').hidden=false;$('#stats').innerHTML=`<div><b>${d.stats.total}</b>Demandes</div><div><b>${d.stats.newRequests}</b>À vérifier</div><div><b>${d.stats.approved}</b>Validées</div><div><b>${d.stats.claimsOpen}</b>Réclamations ouvertes</div><div><b>${d.stats.claimsResolved}</b>Réclamations traitées</div>`;$('#wavenumber').value=d.settings.waveNumber;$('#waveqrurl').value=d.settings.waveQrUrl||'';$('#transactions').innerHTML=d.transactions.map(x=>`<div class="item"><strong>Référence demande : ${esc(x.reference||x.id)}</strong>${esc(x.service||x.offer)} · ${Number(x.amount).toLocaleString('fr-FR')} FCFA · ${esc(x.operator)} · ${esc(x.phone)}<br><span class="status">${esc(x.status)}</span><br><small>Demandée le ${dt(x.createdAt)}${x.decision?.at?' · Décision le '+dt(x.decision.at):''}</small>${requestButtons(x)}</div>`).join('')||'Aucune demande.';$('#claims').innerHTML=d.claims.map(x=>`<div class="item"><strong>Référence réclamation : ${esc(x.reference)}</strong><strong>${esc(x.subject)}</strong>${esc(x.message)}<br>Référence demande : ${esc(x.transactionReference||'Non indiquée')} · <span class="status">${esc(x.status)}</span><br><small>Créée le ${dt(x.createdAt)}${x.updatedAt?' · Mise à jour le '+dt(x.updatedAt):''}</small><br>${claimButtons(x)}</div>`).join('')||'Aucune réclamation.';$('#audit').innerHTML=d.audit.map(x=>`<div class="item"><strong>${esc(x.event)}</strong>${dt(x.at)} · ${esc(x.actor)}</div>`).join('');bindActionButtons();if(centralKey)loadCentral()}catch(e){$('#msg').textContent=e.message}}
function bindActionButtons(){document.querySelectorAll('[data-paid]').forEach(b=>b.onclick=async()=>{await api('/api/admin/transactions/'+b.dataset.id+'/payment-confirmed',{method:'POST'});load()});document.querySelectorAll('[data-decision]').forEach(b=>b.onclick=async()=>{await api('/api/admin/transactions/'+b.dataset.id+'/decision',{method:'POST',body:JSON.stringify({decision:b.dataset.decision})});load()});document.querySelectorAll('[data-claim-save]').forEach(b=>b.onclick=async()=>{const id=b.dataset.claimSave;await api('/api/admin/claims/'+id+'/update',{method:'POST',body:JSON.stringify({status:document.querySelector('[data-claim-status="'+id+'"]').value,note:document.querySelector('[data-claim-note="'+id+'"]').value})});load()})}
function chart(d){const totals=d.daily.map(x=>x.counts.reduce((a,b)=>a+b.count,0)),max=Math.max(1,...totals);return d.daily.map((x,i)=>`<div class="chart-row"><small>${x.day.slice(5).split('-').reverse().join('/')}</small><div class="chart-bar" style="width:${Math.max(3,totals[i]/max*100)}%">${x.counts.filter(c=>c.count).map(c=>`${esc(c.label)}: ${c.count}`).join(' · ')||'0'}</div><small>${totals[i]}</small></div>`).join('')}
async function loadCentral(){try{const d=await api('/api/admin/central/overview');$('#terminals').innerHTML=d.admins.map(a=>`<div class="item terminal"><span class="light ${a.active?'online':'offline'}" title="${a.active?'Connecté':'Hors ligne'}"></span><strong>${esc(a.terminal)}</strong><br><small>${esc(a.email)} · ${a.role==='primary'?'Administrateur principal':'Administrateur'}<br>${a.active?'Connecté':'Hors ligne'} · ${workTime(a.workedMinutes)} travaillées · ${a.validated} demande(s) validée(s)</small>${a.role==='admin'?`<div><input id="reset-${a.id}" inputmode="numeric" maxlength="4" placeholder="Nouveau code (4 chiffres)"><button data-reset="${a.id}">Réinitialiser</button></div>`:''}</div>`).join('');$('#chart').innerHTML=chart(d);document.querySelectorAll('[data-reset]').forEach(b=>b.onclick=async()=>{const code=$('#reset-'+b.dataset.reset).value;try{await api('/api/admin/central/admins/'+b.dataset.reset+'/reset-code',{method:'POST',body:JSON.stringify({code})});$('#adminmsg').textContent='Code administrateur réinitialisé.';loadCentral()}catch(e){$('#adminmsg').textContent=e.message}})}catch(e){centralKey='';$('#central-content').hidden=true;$('#central-lock').hidden=false;$('#centralmsg').textContent=e.message}}
function logout(){token='';centralKey='';clearInterval(poller);$('#panel').hidden=true;$('#gate').hidden=false;$('#adminlogout').hidden=true;$('#password').value='';$('#msg').textContent='Déconnecté.'}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));document.querySelectorAll('.showpass').forEach(c=>c.onchange=()=>c.dataset.target.split(',').forEach(id=>{const e=$('#'+id);if(e)e.type=c.checked?'text':'password'}));
$('#connect').onclick=async()=>{try{const d=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('#email').value,password:$('#password').value})}).then(r=>r.json());if(!d.token)throw Error(d.error);token=d.token;await load();clearInterval(poller);poller=setInterval(()=>{if(!document.activeElement?.matches('input,textarea,select')){api('/api/admin/heartbeat',{method:'POST'}).then(load).catch(e=>$('#msg').textContent=e.message)}},5000)}catch(e){$('#msg').textContent=e.message}};
$('#adminlogout').onclick=logout;$('#savewave').onclick=async()=>{try{await api('/api/admin/payment-settings',{method:'PUT',body:JSON.stringify({waveNumber:$('#wavenumber').value,waveQrUrl:$('#waveqrurl').value})});$('#msg').textContent='Paramètres Wave enregistrés.'}catch(e){$('#msg').textContent=e.message}};
$('#unlockcentral').onclick=async()=>{try{const d=await api('/api/admin/central/unlock',{method:'POST',body:JSON.stringify({code:$('#centralcode').value})});centralKey=d.key;$('#centralcode').value='';$('#central-lock').hidden=true;$('#central-content').hidden=false;loadCentral()}catch(e){$('#centralmsg').textContent=e.message}};
$('#createadmin').onclick=async()=>{try{await api('/api/admin/central/admins',{method:'POST',body:JSON.stringify({terminal:$('#adminterminal').value,email:$('#adminemail').value,password:$('#admincode').value})});$('#adminmsg').textContent='Administrateur créé.';$('#adminterminal').value='';$('#adminemail').value='';$('#admincode').value='';loadCentral()}catch(e){$('#adminmsg').textContent=e.message}};
$('#changecode').onclick=async()=>{try{await api('/api/admin/change-password',{method:'POST',body:JSON.stringify({currentPassword:$('#currentcode').value,newPassword:$('#newcode').value})});$('#codemsg').textContent='Code principal modifié.';$('#currentcode').value='';$('#newcode').value=''}catch(e){$('#codemsg').textContent=e.message}};
$('#changeemail').onclick=async()=>{try{const d=await api('/api/admin/change-email',{method:'POST',body:JSON.stringify({newEmail:$('#newemail').value,currentPassword:$('#emailcode').value})});$('#emailmsg').textContent='E-mail modifié : '+d.email;$('#email').value=d.email;$('#newemail').value='';$('#emailcode').value=''}catch(e){$('#emailmsg').textContent=e.message}};
