/* Konekt MVP API - replace JSON persistence with PostgreSQL before production. */
const http = require('http');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const PORT = process.env.PORT || 8080;
const JWT_SECRET = process.env.KONEKT_JWT_SECRET || 'development-only-change-this-secret';
const WEBHOOK_SECRET = process.env.KONEKT_WEBHOOK_SECRET || 'development-webhook-secret';
if(process.env.NODE_ENV==='production' && (!process.env.KONEKT_JWT_SECRET || !process.env.KONEKT_WEBHOOK_SECRET || !process.env.ADMIN_EMAIL || !process.env.ADMIN_PASSWORD)) throw Error('Secrets et compte administrateur obligatoires en production.');
const DATA = process.env.DATA_PATH || path.join(__dirname, 'data.json');
const PUBLIC = path.join(__dirname, 'public');
const offers = { Orange:[['500 Mo',500,'24 h'],['1,5 Go',1000,'7 jours'],['4 Go',2000,'15 jours'],['12 Go',5000,'30 jours']], MTN:[['750 Mo',500,'24 h'],['2 Go',1000,'7 jours'],['5 Go',2000,'15 jours'],['15 Go',5000,'30 jours']], Moov:[['600 Mo',500,'24 h'],['1,8 Go',1000,'7 jours'],['4,5 Go',2000,'15 jours'],['13 Go',5000,'30 jours']] };
const catalog={Orange:['Recharge unité','Forfait appel','Forfait internet','WiFi Orange'],MTN:['Recharge unité','Forfait appel','Forfait internet','WiFi MTN'],Moov:['Recharge unité','Appel Izi','Appel Foli','Internet Izi','Internet Foli','WiFi Moov']};
const suggested=[200,500,1000,2000,5000];

function load(){ if(fs.existsSync(DATA)) return JSON.parse(fs.readFileSync(DATA)); const admin=process.env.ADMIN_EMAIL||'admin@konekt.local'; const password=process.env.ADMIN_PASSWORD||'ChangeMe!2026'; return {users:[{id:'usr_admin',email:admin,role:'primary',salt:'bootstrap',password:hash(password,'bootstrap')}],transactions:[],audit:[],idempotency:{}}; }
let db=load(); if(!db.users.some(u=>u.role==='primary')&&db.users[0])db.users[0].role='primary'; db.settings=db.settings||{waveNumber:'0759790762',waveQrUrl:''}; db.claims=db.claims||[]; function save(){fs.writeFileSync(DATA,JSON.stringify(db,null,2));}
db.adminSessions=db.adminSessions||{};
const centralAccess=new Map();
const attempts=new Map(); function allowed(req){const ip=req.socket.remoteAddress||'unknown', now=Date.now(), recent=(attempts.get(ip)||[]).filter(t=>now-t<60000);if(recent.length>=60)return false;recent.push(now);attempts.set(ip,recent);return true;}
function hash(v,salt){return crypto.scryptSync(v,salt,64).toString('hex');} function uid(prefix){return prefix+'_'+crypto.randomBytes(10).toString('hex');}
function sign(body){return crypto.createHmac('sha256',JWT_SECRET).update(body).digest('base64url');}
function token(user){const body=Buffer.from(JSON.stringify({id:user.id,email:user.email,role:user.role,exp:Date.now()+86400000})).toString('base64url');return body+'.'+sign(body);}
function touchAdmin(u){if(!u||!['admin','primary'].includes(u.role))return;const now=Date.now(),s=db.adminSessions[u.id];if(!s||now-s.lastSeen>30000)db.adminSessions[u.id]={terminal:u.terminal||(u.role==='primary'?'Admin central':'Terminal admin'),startedAt:now,lastSeen:now,totalMs:s?.totalMs||0};else s.lastSeen=now;save();}
function auth(req, role){const raw=(req.headers.authorization||'').replace('Bearer ',''); const [body,s]=raw.split('.'); const expected=body?Buffer.from(sign(body)):Buffer.alloc(0), received=s?Buffer.from(s):Buffer.alloc(0); if(!body||!s||expected.length!==received.length||!crypto.timingSafeEqual(expected,received)) return null; try { const p=JSON.parse(Buffer.from(body,'base64url'));if(!(p.exp>Date.now()&&(!role||p.role===role||(role==='admin'&&p.role==='primary'))))return null;touchAdmin(p);return p; } catch{return null;} }
function central(req){const key=req.headers['x-central-access'],data=key&&centralAccess.get(key);if(!data||data.expires<Date.now())return null;return data;}
function centralStats(){const now=Date.now(),admins=db.users.filter(u=>['admin','primary'].includes(u.role));return {admins:admins.map((u,i)=>{const s=db.adminSessions[u.id],active=!!s&&now-s.lastSeen<30000,worked=(s?.totalMs||0)+(active?now-s.startedAt:0);return {id:u.id,email:u.email,terminal:u.terminal||(u.role==='primary'?'Admin central':'Terminal '+(i+1)),role:u.role,active,workedMinutes:Math.floor(worked/60000),validated:db.transactions.filter(t=>t.decision?.by===u.id&&t.status==='approved_for_manual_topup').length};}),daily:Array.from({length:7},(_,n)=>{const day=new Date(now-(6-n)*86400000).toISOString().slice(0,10);return {day,counts:admins.map((u,i)=>({id:u.id,label:u.terminal||(u.role==='primary'?'Admin central':'Terminal '+(i+1)),count:db.transactions.filter(t=>t.decision?.by===u.id&&t.status==='approved_for_manual_topup'&&String(t.decision.at||'').slice(0,10)===day).length}))};})};}
function audit(actor,event,details){db.audit.unshift({id:uid('aud'),at:new Date().toISOString(),actor,event,details});db.audit=db.audit.slice(0,500);save();}
function respond(res,status,data){res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(JSON.stringify(data));}
function read(req){return new Promise((resolve,reject)=>{let b='';req.on('data',c=>{b+=c;if(b.length>100000)reject(Error('Trop volumineux'));});req.on('end',()=>{try{resolve({raw:b,json:b?JSON.parse(b):{}})}catch{reject(Error('JSON invalide'))}});});}
function safeUser(u){return {id:u.id,email:u.email,role:u.role};}
function topup(tx){ /* Replace with authorised top-up provider call. */ tx.topupStatus='delivered';tx.status='completed';tx.deliveredAt=new Date().toISOString();audit('provider','topup.delivered',{transactionId:tx.id,operator:tx.operator}); }
function createPaymentIntent(tx){ /* Replace with approved payment partner. No PIN/OTP is handled by Konekt. */ return {provider:'sandbox_mobile_money',reference:'PAY-'+tx.id.slice(-10),checkoutUrl:null};}
function validNumber(operator,service,phone){const p=(phone||'').replace(/\s/g,'');const prefix=service.startsWith('WiFi')?({Orange:'27',Moov:'01',MTN:'05'}[operator]):({Orange:'07',Moov:'01',MTN:'05'}[operator]);return new RegExp('^'+prefix+'\\d{8}$').test(p);}

const server=http.createServer(async(req,res)=>{try{
 if(!allowed(req)){res.writeHead(429,{'Content-Type':'application/json','Retry-After':'60'});return res.end(JSON.stringify({error:'Trop de requêtes. Réessayez dans une minute.'}));}
 res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');
 const url=new URL(req.url,'http://localhost'); const method=req.method;
 if(method==='GET'&&url.pathname==='/healthz')return respond(res,200,{ok:true});
 if(method==='GET'&&url.pathname==='/api/offers') return respond(res,200,offers);
 if(method==='GET'&&url.pathname==='/api/catalog') return respond(res,200,{catalog,suggested});
 if(method==='GET'&&url.pathname==='/api/payment-instructions') return respond(res,200,{waveNumber:db.settings.waveNumber,waveQrUrl:db.settings.waveQrUrl});
 if(method==='POST'&&url.pathname==='/api/auth/register'){const {email,password}= (await read(req)).json; if(!/^\S+@\S+\.\S+$/.test(email||'')||!/^\d{4}$/.test(String(password||'')))return respond(res,400,{error:'Indiquez un e-mail valide et un code de 4 chiffres.'}); if(db.users.some(u=>u.email===email.toLowerCase()))return respond(res,409,{error:'Ce compte existe déjà.'});const salt=crypto.randomBytes(16).toString('hex'),u={id:uid('usr'),email:email.toLowerCase(),role:'customer',salt,password:hash(password,salt)};db.users.push(u);audit(u.id,'user.registered',{email:u.email});return respond(res,201,{token:token(u),user:safeUser(u)});}
 if(method==='POST'&&url.pathname==='/api/auth/login'){const {email,password}=(await read(req)).json;const u=db.users.find(x=>x.email===(email||'').toLowerCase());if(!u||hash(password||'',u.salt)!==u.password)return respond(res,401,{error:'Identifiants incorrects.'});touchAdmin(u);audit(u.id,'user.logged_in',{});return respond(res,200,{token:token(u),user:safeUser(u)});}
 if(method==='POST'&&url.pathname==='/api/admin/heartbeat'){const u=auth(req,'admin');if(!u)return respond(res,403,{error:'Administrateur requis.'});return respond(res,200,{ok:true});}
 if(method==='POST'&&url.pathname==='/api/admin/central/unlock'){const u=auth(req,'admin');if(!u)return respond(res,403,{error:'Administrateur requis.'});const b=(await read(req)).json,primary=db.users.find(x=>x.role==='primary');if(!primary||hash(String(b.code||''),primary.salt)!==primary.password)return respond(res,401,{error:'Code de l’administrateur principal incorrect.'});const key=crypto.randomBytes(24).toString('hex');centralAccess.set(key,{userId:u.id,expires:Date.now()+1800000});return respond(res,200,{key,expiresAt:new Date(Date.now()+1800000).toISOString()});}
 if(method==='GET'&&url.pathname==='/api/admin/central/overview'){const u=auth(req,'admin');if(!u||!central(req))return respond(res,403,{error:'Accès administrateur central requis.'});return respond(res,200,centralStats());}
 if(method==='POST'&&url.pathname==='/api/admin/central/admins'){const u=auth(req,'admin');if(!u||!central(req))return respond(res,403,{error:'Accès administrateur central requis.'});const b=(await read(req)).json,email=String(b.email||'').trim().toLowerCase(),password=String(b.password||''),terminal=String(b.terminal||'').trim().slice(0,40);if(!/^\S+@\S+\.\S+$/.test(email)||!/^\d{4}$/.test(password)||terminal.length<3)return respond(res,400,{error:'Indiquez un e-mail, un code de 4 chiffres et un nom de terminal.'});if(db.users.some(x=>x.email===email))return respond(res,409,{error:'Cet e-mail est déjà utilisé.'});const salt=crypto.randomBytes(16).toString('hex'),admin={id:uid('adm'),email,role:'admin',terminal,salt,password:hash(password,salt)};db.users.push(admin);audit(u.id,'admin.created',{adminId:admin.id,terminal});save();return respond(res,201,safeUser(admin));}
 if(method==='POST'&&url.pathname.match(/^\/api\/admin\/central\/admins\/[^/]+\/reset-code$/)){const u=auth(req,'admin');if(!u||!central(req))return respond(res,403,{error:'Accès administrateur central requis.'});const target=db.users.find(x=>x.id===url.pathname.split('/')[5]),b=(await read(req)).json,code=String(b.code||'');if(!target||target.role!=='admin')return respond(res,404,{error:'Administrateur introuvable.'});if(!/^\d{4}$/.test(code))return respond(res,400,{error:'Le code doit contenir 4 chiffres.'});target.salt=crypto.randomBytes(16).toString('hex');target.password=hash(code,target.salt);audit(u.id,'admin.code_reset',{adminId:target.id});save();return respond(res,200,{ok:true});}
 if(method==='GET'&&url.pathname==='/api/me/transactions'){const u=auth(req);if(!u)return respond(res,401,{error:'Connexion requise.'});return respond(res,200,db.transactions.filter(t=>t.userId===u.id));}
 if(method==='GET'&&url.pathname==='/api/me/claims'){const u=auth(req);if(!u)return respond(res,401,{error:'Connexion requise.'});return respond(res,200,db.claims.filter(c=>c.userId===u.id));}
 if(method==='POST'&&url.pathname==='/api/claims'){const u=auth(req);if(!u)return respond(res,401,{error:'Connexion requise.'});const b=(await read(req)).json,message=String(b.message||'').trim(),subject=String(b.subject||'').trim(),reference=String(b.reference||'').trim();if(subject.length<3||message.length<10||message.length>2000)return respond(res,400,{error:'Indiquez un objet et une réclamation détaillée.'});const claim={id:uid('clm'),reference:'REC-'+Date.now().toString(36).toUpperCase()+'-'+crypto.randomBytes(2).toString('hex').toUpperCase(),userId:u.id,subject,message,transactionReference:reference,phone:String(b.phone||'').replace(/\s/g,''),status:'open',createdAt:new Date().toISOString(),updates:[]};db.claims.unshift(claim);audit(u.id,'claim.created',{claimId:claim.id,reference:claim.reference});return respond(res,201,claim);}
 if(method==='POST'&&url.pathname==='/api/transactions'){const u=auth(req);if(!u)return respond(res,401,{error:'Connexion requise.'});const key=req.headers['idempotency-key'];if(!key)return respond(res,400,{error:'Clé d’idempotence requise.'});if(db.idempotency[key])return respond(res,200,db.idempotency[key]);const b=(await read(req)).json, amount=Number(b.amount);if(!catalog[b.operator]?.includes(b.service)||!Number.isInteger(amount)||amount<100||amount>500000||!validNumber(b.operator,b.service,b.phone))return respond(res,400,{error:'Service, montant ou numéro invalide.'});const tx={id:uid('tx'),reference:'KON-'+Date.now().toString(36).toUpperCase()+'-'+crypto.randomBytes(2).toString('hex').toUpperCase(),userId:u.id,phone:b.phone.replace(/\s/g,''),operator:b.operator,service:b.service,offer:b.service,amount,method:'Wave',status:'request_received',paymentStatus:'awaiting_wave_payment',topupStatus:'not_requested',createdAt:new Date().toISOString()};db.transactions.unshift(tx);db.idempotency[key]=tx;audit(u.id,'request.received',{transactionId:tx.id,reference:tx.reference,amount:tx.amount,operator:tx.operator});return respond(res,201,tx);}
 if(method==='POST'&&url.pathname==='/api/webhooks/payment'){const {raw,json}=await read(req);const received=req.headers['x-konekt-signature']||'';const expected=crypto.createHmac('sha256',WEBHOOK_SECRET).update(raw).digest('hex');if(received.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(received),Buffer.from(expected))){audit('system','webhook.rejected',{});return respond(res,401,{error:'Signature invalide.'});}const tx=db.transactions.find(t=>t.id===json.transactionId);if(!tx)return respond(res,404,{error:'Transaction introuvable.'});if(json.status==='paid'&&tx.status==='payment_pending'){tx.status='paid';audit('payment_partner','payment.confirmed',{transactionId:tx.id});topup(tx);save();}return respond(res,200,{ok:true});}
 if(method==='POST'&&url.pathname.match(/^\/api\/transactions\/[^/]+\/refund$/)){const u=auth(req,'admin');if(!u)return respond(res,403,{error:'Administrateur requis.'});const tx=db.transactions.find(t=>t.id===url.pathname.split('/')[3]);if(!tx)return respond(res,404,{error:'Transaction introuvable.'});if(tx.status!=='completed')return respond(res,409,{error:'Cette transaction ne peut pas être remboursée.'});tx.status='refund_pending';tx.refund={requestedAt:new Date().toISOString(),by:u.id};audit(u.id,'refund.requested',{transactionId:tx.id});save();return respond(res,200,tx);}
 if(method==='POST'&&url.pathname.match(/^\/api\/admin\/transactions\/[^/]+\/payment-confirmed$/)){const u=auth(req,'admin');if(!u)return respond(res,403,{error:'Administrateur requis.'});const tx=db.transactions.find(t=>t.id===url.pathname.split('/')[4]);if(!tx)return respond(res,404,{error:'Demande introuvable.'});if(tx.status!=='request_received')return respond(res,409,{error:'Paiement déjà traité.'});tx.paymentStatus='wave_payment_confirmed';tx.status='payment_confirmed';audit(u.id,'wave.payment_confirmed',{transactionId:tx.id,reference:tx.reference});save();return respond(res,200,tx);}
 if(method==='POST'&&url.pathname.match(/^\/api\/admin\/transactions\/[^/]+\/decision$/)){const u=auth(req,'admin');if(!u)return respond(res,403,{error:'Administrateur requis.'});const tx=db.transactions.find(t=>t.id===url.pathname.split('/')[4]),decision=(await read(req)).json.decision;if(!tx)return respond(res,404,{error:'Demande introuvable.'});if(!['payment_confirmed','request_received'].includes(tx.status)||!['approved','rejected'].includes(decision))return respond(res,409,{error:'Cette décision est impossible.'});tx.status=decision==='approved'?'approved_for_manual_topup':'rejected';tx.decision={by:u.id,at:new Date().toISOString()};audit(u.id,decision==='approved'?'request.approved':'request.rejected',{transactionId:tx.id});save();return respond(res,200,tx);}
 if(method==='PUT'&&url.pathname==='/api/admin/payment-settings'){const u=auth(req,'admin');if(!u)return respond(res,403,{error:'Administrateur requis.'});const b=(await read(req)).json;if(!/^0\d{9}$/.test(b.waveNumber||''))return respond(res,400,{error:'Numéro Wave invalide.'});db.settings={waveNumber:b.waveNumber,waveQrUrl:String(b.waveQrUrl||'').slice(0,500)};audit(u.id,'payment.settings_updated',{});save();return respond(res,200,db.settings);}
 if(method==='POST'&&url.pathname==='/api/admin/change-password'){const u=auth(req,'admin');if(!u||!central(req))return respond(res,403,{error:'Accès administrateur central requis.'});const b=(await read(req)).json,admin=db.users.find(x=>x.id===u.id);if(!admin||hash(String(b.currentPassword||''),admin.salt)!==admin.password)return respond(res,401,{error:'Code actuel incorrect.'});if(!/^\d{4}$/.test(String(b.newPassword||'')))return respond(res,400,{error:'Le nouveau code doit contenir exactement 4 chiffres.'});admin.salt=crypto.randomBytes(16).toString('hex');admin.password=hash(b.newPassword,admin.salt);audit(u.id,'admin.password_changed',{});return respond(res,200,{ok:true});}
 if(method==='POST'&&url.pathname==='/api/admin/change-email'){const u=auth(req,'admin');if(!u||!central(req))return respond(res,403,{error:'Accès administrateur central requis.'});const b=(await read(req)).json,admin=db.users.find(x=>x.id===u.id),email=String(b.newEmail||'').trim().toLowerCase();if(!admin||hash(String(b.currentPassword||''),admin.salt)!==admin.password)return respond(res,401,{error:'Code actuel incorrect.'});if(!/^\S+@\S+\.\S+$/.test(email))return respond(res,400,{error:'Nouvel e-mail invalide.'});if(db.users.some(x=>x.id!==admin.id&&x.email===email))return respond(res,409,{error:'Cet e-mail est déjà utilisé.'});admin.email=email;audit(u.id,'admin.email_changed',{email});save();return respond(res,200,{ok:true,email});}
 if(method==='POST'&&url.pathname.match(/^\/api\/admin\/claims\/[^/]+\/update$/)){const u=auth(req,'admin');if(!u)return respond(res,403,{error:'Administrateur requis.'});const claim=db.claims.find(c=>c.id===url.pathname.split('/')[4]),b=(await read(req)).json,note=String(b.note||'').trim();if(!claim)return respond(res,404,{error:'Réclamation introuvable.'});if(!['open','in_review','resolved','closed'].includes(b.status)||note.length>1000)return respond(res,400,{error:'Mise à jour invalide.'});claim.status=b.status;claim.updatedAt=new Date().toISOString();if(note)claim.updates.unshift({at:claim.updatedAt,by:u.id,note,status:b.status});audit(u.id,'claim.updated',{claimId:claim.id,status:b.status});save();return respond(res,200,claim);}
 if(method==='GET'&&url.pathname==='/api/admin/overview'){const u=auth(req,'admin');if(!u)return respond(res,403,{error:'Administrateur requis.'});return respond(res,200,{transactions:db.transactions,claims:db.claims,audit:db.audit,settings:db.settings,stats:{total:db.transactions.length,newRequests:db.transactions.filter(t=>t.status==='request_received').length,approved:db.transactions.filter(t=>t.status==='approved_for_manual_topup').length,claimsOpen:db.claims.filter(c=>['open','in_review'].includes(c.status)).length,claimsResolved:db.claims.filter(c=>['resolved','closed'].includes(c.status)).length}});}
 const file=url.pathname==='/'?'index.html':url.pathname.slice(1);const full=path.resolve(PUBLIC,file);if(!full.startsWith(PUBLIC)||!fs.existsSync(full))return respond(res,404,{error:'Introuvable.'});const types={'.html':'text/html; charset=utf-8','.js':'application/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml'};res.writeHead(200,{'Content-Type':types[path.extname(full)]||'application/octet-stream','X-Content-Type-Options':'nosniff'});fs.createReadStream(full).pipe(res);
 }catch(e){respond(res,400,{error:e.message||'Erreur'});}});
server.listen(PORT,'0.0.0.0',()=>console.log('Planet One: http://0.0.0.0:'+PORT));
